---
title: "RESAMPLING METHODS"
output: html_document
date: "2023-10-23"
---

# Student Details

|                                              |     |
|----------------------------------------------|-----|
| **Student ID Number**                        |135791,136657,136665 |
| **Student Name**                             |Rehema Jemutai, Shirleen Murugi, Adnan Mwendwa |
| **BBIT 4.2 Group**                           | C,C,B |
| **BI Project Group Name/ID (if applicable)** | ... |

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r 1}
if (require("languageserver")) {
  require("languageserver")
} else {
  install.packages("languageserver", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

if (require("caret")) {
  require("caret")
} else {
  install.packages("caret", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## klaR ----
if (require("klaR")) {
  require("klaR")
} else {
  install.packages("klaR", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## e1071 ----
if (require("e1071")) {
  require("e1071")
} else {
  install.packages("e1071", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## readr ----
if (require("readr")) {
  require("readr")
} else {
  install.packages("readr", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## LiblineaR ----
if (require("LiblineaR")) {
  require("LiblineaR")
} else {
  install.packages("LiblineaR", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## naivebayes ----
if (require("naivebayes")) {
  require("naivebayes")
} else {
  install.packages("naivebayes", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

if (!is.element("mlbench", installed.packages()[, 1])) {
  install.packages("mlbench", dependencies = TRUE)  #nolint
}
require("mlbench")

```

```{r STEP 1}
library(readr)
diabetes <- read_csv("data/diabetes.csv")
View(diabetes)

data("PimaIndiansDiabetes")
summary(PimaIndiansDiabetes)
str(PimaIndiansDiabetes)
```

```{r STEP 2}
data("PimaIndiansDiabetes")
summary(PimaIndiansDiabetes)
str(PimaIndiansDiabetes)

#split the dataset
train_index <- createDataPartition(PimaIndiansDiabetes$diabetes,
                                   p = 0.75,
                                   list = FALSE)
PimaIndiansDiabetes_train <- PimaIndiansDiabetes[train_index, ]
PimaIndiansDiabetes_test <- PimaIndiansDiabetes[-train_index, ]

PimaIndiansDiabetes_model_nb_e1071 <- # nolint
  e1071::naiveBayes(diabetes ~ pregnant + glucose + pressure + triceps + insulin + mass +
                      pedigree + age,
                    data = PimaIndiansDiabetes_train)


PimaIndiansDiabetest_model_nb <-
  e1071::naiveBayes(diabetes ~ .,
                    data = PimaIndiansDiabetes_train)

PimaIndiansDiabetes_model_nb_caret <- # nolint
  caret::train(diabetes ~ ., data =
                 PimaIndiansDiabetes_train[, c("pregnant", "glucose", "pressure", "triceps", "insulin",
                                               "mass", "pedigree", "age", "diabetes")],
               method = "naive_bayes")
```

```{r STEP 3A}
predictions_nb_e1071 <-
  predict(PimaIndiansDiabetes_model_nb_e1071,
          PimaIndiansDiabetes_test[, c("pregnant", "glucose", "pressure", "triceps", "insulin",
                                       "mass", "pedigree", "age", "diabetes")])
```

```{r STEP 3B}
predictions_nb_caret <-
  predict(PimaIndiansDiabetes_model_nb_caret,
          PimaIndiansDiabetes_test[, c("pregnant", "glucose", "pressure", "triceps", "insulin",
                                       "mass", "pedigree", "age", "diabetes")])
```

```{r STEP 4A}
print(predictions_nb_e1071)
caret::confusionMatrix(predictions_nb_e1071,
                       PimaIndiansDiabetes_test[, c("pregnant", "glucose", "pressure",
                                                    "triceps", "insulin", "mass",
                                                    "pedigree",
                                                    "age",
                                                    "diabetes" 
                       )]$diabetes)
plot(table(predictions_nb_e1071,
           PimaIndiansDiabetes_test[, c("pregnant", "glucose", "pressure",
                                        "triceps", "insulin", "mass",
                                        "pedigree",
                                        "age",
                                        "diabetes" 
           )]$diabetes))
```


```{r STEP4 B}
print(PimaIndiansDiabetes_model_nb_caret)
caret::confusionMatrix(predictions_nb_caret,
                       PimaIndiansDiabetes_test[, c("pregnant", "glucose", "pressure",
                                                    "triceps", "insulin", "mass",
                                                    "pedigree",
                                                    "age",
                                                    "diabetes" 
                       )]$diabetes)
plot(table(predictions_nb_caret,
           PimaIndiansDiabetes_test[, c("pregnant", "glucose", "pressure",
                                        "triceps", "insulin", "mass",
                                        "pedigree",
                                        "age",
                                        "diabetes" 
           )]$diabetes))
```

```{r STEP 5A}
train_control <- trainControl(method = "repeatedcv", number = 5, repeats = 3)

PimaIndiansDiabetes_model_svm <-
  caret::train(diabetes ~ ., data = PimaIndiansDiabetes_train,
               trControl = train_control, na.action = na.omit,
               method = "svmLinearWeights2", metric = "Accuracy")
```


```{r STEP 5B}
predictions_svm <- predict(PimaIndiansDiabetes_model_svm, PimaIndiansDiabetes_test[, 1:9])
```


```{r STEP 5C }
print(PimaIndiansDiabetes_model_svm)
caret::confusionMatrix(predictions_svm, PimaIndiansDiabetes_test$diabetes)
```

```{r STEP 6A }
  train_control <- trainControl(method = "LOOCV")

PimaIndiansDiabetes_model_nb_loocv <-
  caret::train(diabetes ~ ., data = PimaIndiansDiabetes_train,
               trControl = train_control, na.action = na.omit,
               method = "naive_bayes", metric = "Accuracy")
```


```{r STEP 6B }
predictions_nb_loocv <-
  predict(PimaIndiansDiabetes_model_nb_loocv, PimaIndiansDiabetes_test[, 1:9])
```

```{r STEP 6c }
print(PimaIndiansDiabetes_model_nb_loocv)
caret::confusionMatrix(predictions_nb_loocv, PimaIndiansDiabetes_test$diabetes)
```



